### ISSUE TITLE
Avoiding Tracing Public Resource URLs

### ISSUE THREAD

**Issue by nevi-me** [opentracing-contrib/javascript-express#6]
I'm implementing tracing in a project, using Jaeger as the backend. I'm getting a lot of noise with URLs for CSS, JS and other static assets being traced. Is there a way of disabling this?

Thanks

**Comment by rnburn** [comment]
Yes, when you call `app.use` to set up the tracing middleware, you can pass an optional argument to have it match a subset of requests. Look at the examples in the [using-middleware](http://expressjs.com/en/guide/using-middleware.html#middleware.application) documentation.

**Comment by nevi-me** [comment]
Thanks, looking at the documentation, there doesn't seem to be a way of saying "match all routes that aren't CSS/JS requests".

I'm looking at adding some logic to exclude routes that I'm not interested in, will let you know how that goes.
